LSRCS = prologixs.c open-gpib-inet.c serial.c hp16500ip.c fileio.c open-gpib-param.c support.c
L2SRCS = $(LSRCS) open-gpib.c
LOBJS = $(patsubst %.c,%.o,$(L2SRCS))
LHDRS = open-gpib.h prologixs.h open-gpib-ip.h serial.h fileio.h 
LIB=libopen-gpib.a
PACKAGE_VERSION?=$(shell ./get-version)

CFLAGS+=-I .
all: $(LIB)

$(LOBJS): interface.h open-gpib.h

interface.h:
	./build-interfaces $(LSRCS)

open-gpib.h: interface.h
	./build-interfaces "header"

open-gpib.o: CFLAGS+=-D_ALLOC_REGISTER_ -DPACKAGE_VERSION='"$(PACKAGE_VERSION)"'

%.o: %.c %.h
	gcc -Wall $(CFLAGS) -c -o $@ $<

#libopen-gpib.a: open-gpib.a

$(LIB): $(LOBJS)
	ar -cr $@ $^

clean:
	-rm $(LOBJS) $(LIB) interface.h open-gpib.h
#libopen-gpib.a: open-gpib.o open-gpib.a

