#!/bin/bash
# Quick n dirty script to save some typing
#

# base
get_waveform () {
./get_hp_1653xx_scope -a 192.168.0.200 -t 14 -c ch1 -c ch2 -c ch3 -c ch4 -g -o "$1"
}
# base type title
plot_waveform () {
./plot-file -f 2 -k "$2" -o "$1.png" -p "$1.plot" -t "$3" $4 " $1.ch1" "$1.ch2" "$1.ch3" "$1.ch4"
}

usage() {
	echo "usage: get_hp_plot <options>"
	echo "where options are:"
	echo " -b bname set base name to bname"
	echo " -k pkind set plot kind to pkind (png or x11)"
	echo " -h this screen"
	echo " -m mode set mode to plot,get,or all (required)"
	echo " -t ptitle set title of plot to ptitle"
	echo " -p popts send popts to plot-file"
  echo "ex: ./get_plot -k png -b myfile -t \"This is My File\""
}
if [ $# -lt 1 ]; then
   usage
   exit 1
fi
MODE=""
while  getopts b:k:hm:p:t: opt ; do
  case $opt in	
    b) base="$OPTARG";;
    k) type="$OPTARG";;
    h) usage;;
    m) MODE="$OPTARG"
       #p) MODE="plot";;
       #g) MODE="get";;
       #a) MODE="all";;
       #*) echo "Unknown mode $OPTARG."
       #usage;;
       #esac
       ;;
     p) popts="$OPTARG" ;;
     t) title="$OPTARG";;
     *)echo "Unknown mode $OPTARG."
       usage;;
   esac 
done   
if [ -z "$base" ] || [ -z "$type" ] || [ -z "$MODE" ]; then
  echo "have to specify at least -b & -k"
  usage
fi
if [ "$MODE" = "all" ] || [ "$MODE" = "get" ]; then
get_waveform "$base"
fi
if [ "$MODE" = "all" ] || [ "$MODE" = "plot" ]; then
plot_waveform "$base" "$type" "$title" "$popts"
fi
