#!/bin/bash
if [ $# -lt 1 ]; then
	echo "Use: fname <ch>"
	echo " Where fname is the base name of the files created from a trace grab"
	echo " From the HP scope. We assume channel 1 if more channels are specified,"
	echo " Then more -c will be added to the scope data command"
	exit 1
fi
fname="$1"
chan=($2 $3 $4 $5 $6 $7 $8 $9)
if [ -n "${chan[4]}" ]; then
	type=13
else
	type=14
fi
let i=0
let sub=0
while [ $i -lt ${#chan[@]} ]; do
	c=${chan[$i]}
	let fn=i+1
	let c=c-sub
	CH="$CH -c $c"
	INF="$INF $fname.$fn"
	if [ $i -eq 3 ]; then
		src/get_hp_1653xx_scope -t $type -a 192.168.0.200 -g -v $CH -o $fname
		sub=4
		CH=''
		type=14
	fi
	let i=i+1
done
echo "CH='$CH'"
if [ -n "${chan[4]}" ]; then
	t=$(mktemp -d)
	mv $fname* $t
fi

src/get_hp_1653xx_scope -t $type -a 192.168.0.200 -g -v $CH -o $fname
if [ -n "${chan[4]}" ]; then
	for x in 1 2 3 4; do
		let y=x+4
		mv $fname.$x $fname.$y
	done
	mv $t/* .
	rm -r $t
fi

scripts/plot-file -f 2 -k png -p $fname.plot -o $fname.1.png $INF
