# \file ******************************************************************
#\n\b File:        Makefile
#\n\b Author:      Doug Springer
#\n\b Company:     DNK Designs Inc.
#\n\b Date:        10/05/2007  7:56 am
#\n\b Description: 
#*/ /************************************************************************
#Change Log: \n
#
# This file is part of OpenGPIB.
# For details, see http://opengpib.sourceforge.net/projects
#
# Copyright (C) 2008-2009 Doug Springer <gpib@rickyrockrat.net>
#
#    OpenGPIB is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License version 3 
#    as published by the Free Software Foundation. Note that permission 
#    is not granted to redistribute this program under the terms of any
#    other version of the General Public License.
#
#    OpenGPIB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with OpenGPIB.  If not, see <http://www.gnu.org/licenses/>.
#    
#		The License should be in the file called COPYING.

#-std=c99

VERSION ?= 0.12

PACKAGE = opengpib

TARGETS=tek2gplot get_tek_waveform get_hp_1653xx_scope get_hp_16555_waveform \
calc_area_under_curve networkanalyzer parse_16500_config hp16500

CSRCS = get_hp_1653xx_scope.c get_tek_waveform.c  networkanalyzer.c \
 tek2gplot.c calc_area_under_curve.c parse_16500_config.c  get_hp_16555_waveform.c 

HDRS = hp16500.h 
CFLAGS+=-Wall -I. -I ../lib
OG_LIB=../lib/libopen-gpib.a
HAVE_LA2VCD=$(shell pkg-config --libs libla2vcd2)
LDFLAGS+=-lm -L../lib -lopen-gpib
ifneq ($(HAVE_LA2VCD),)
	CFLAGS+=-DHAVE_LIBLA2VCD2
	LDFLAGS+=$(HAVE_LA2VCD)
endif
MISC = COPYING README Makefile makepng runcal ChangeLog

DISTFILES = $(MISC) $(HDRS) $(CSRCS)
DISTNAME = $(PACKAGE)-$(VERSION)

all: help

help:
	@echo "Usage: make defs target"
	@echo "Targets are: dist clean build"
	@echo "To get the vcd output (input for gtkwave), build with"	
	@echo " make LA2VCD_LIB=/path/to/la2vcd.lib build"
	@echo " la2vcd should be available from the same location"
	@echo " you obtained this software."

build: $(OG_LIB) $(TARGETS)

#hp16500.o hp16500ip.o hp1655x.o hp1653x.o: CFLAGS+=-std=c99 

get_tek_waveform.o: CFLAGS+= -D_GLOBAL_TEK_2440_ 


tek2gplot.o: get_tek_waveform.o tek2gplot.c $(OG_LIB)

tek2gplot: tek2gplot.o $(OG_LIB)
	gcc $(CFLAGS) -o $@ $^ $(LDFLAGS)
	
calc_area_under_curve: calc_area_under_curve.o $(OG_LIB)
	gcc $(CFLAGS) -o $@ $^ $(LDFLAGS)

$(OG_LIB):
	$(MAKE) -C ../lib -f Makefile.orig

hp16500.o: hp16500.c  hp16500.h	

hp16500ip.o: hp16500ip.c  hp16500ip.h	

hp16500.lib: hp16500.o 
	ar -cr $@ $^

get_tek_waveform:	get_tek_waveform.o $(OG_LIB)
	gcc $(CFLAGS) -o $@ $^ $(LDFLAGS)
	
get_hp_1653xx_scope.o get_hp_16555_waveform.o parse_16500_config.o: hp16500.h


get_hp_1653xx_scope: get_hp_1653xx_scope.o $(OG_LIB) hp16500.lib hp1653x.o 
	gcc $(CFLAGS) -lm -o $@ $^ $(LDFLAGS)
	
get_hp_16555_waveform: get_hp_16555_waveform.o $(OG_LIB) hp16500.lib hp1655x.o
	gcc $(CFLAGS) -lm -o $@ $^ $(LDFLAGS)
	
hp16500.main.o: hp16500.c  hp16500.h
	gcc $(CFLAGS) -DMAIN_QUERY  -c -o $@ hp16500.c

hp16500: hp16500.main.o $(OG_LIB) hp1653x.o
	gcc $(CFLAGS) -lm -o $@ $^
	
test: test.o $(OG_LIB)
	gcc $(CFLAGS) -lm -o $@ $^

%.o: Makefile

parse_16500_config:parse_16500_config.o hp16500.lib $(OG_LIB) hp1655x.o
	gcc $(CFLAGS) -lm -o $@ $^ $(LDFLAGS)

networkanalyzer: networkanalyzer.o $(OG_LIB)
	gcc $(CFLAGS) -lm -o $@ $^

.PHONY: clean
clean:
	-rm *.o *.lib $(TARGETS)

dist: $(DISTFILES)
	-rm -rf $(DISTNAME)
	mkdir $(DISTNAME)
	for f in $(DISTFILES); do ln $$f $(DISTNAME)/$$f; done
	tar --gzip -chf $(DISTNAME).tar.gz $(DISTNAME)
	-rm -rf $(DISTNAME)

